import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class PhoneNumbers {
    public String bestNumber(String number) {
        Sol sol = best(number);
        if (null != sol) return sol.res;
        return null;
    }
    
    private static class Sol{
        int val;
        String res;
        Sol(int v, String r) {
            val = v;
            res = r;
        }
    }
    
    private Sol best(String num) {
        if (2 > num.length()) return null;
        if (3 >= num.length()) return new Sol(val(num), num);
        Sol s1 = best(num.substring(2));
        Sol s2 = best(num.substring(3));
        int v1 = val(num.substring(0,2));
        int v2 = val(num.substring(0,3));
        boolean first;
        if (null == s1) {
            if (null == s2) return null;
            first = false;
        } else {
            if (null == s2) first = true;
            else first = (v1+s1.val) >= (v2+s2.val);
        }
        if (first) {
            s1.val += v1;
            s1.res = num.substring(0,2) + "-" + s1.res;
            return s1;
        } else {
            s2.val += v2;
            s2.res = num.substring(0,3) + "-" + s2.res;
            return s2;
        }
    }

    private int val(String num) {
        if (2 == num.length()) {
            return num.charAt(0) == num.charAt(1) ? 2 : 0;
        }
        boolean b1 = num.charAt(0) == num.charAt(1);
        boolean b2 = num.charAt(0) == num.charAt(2);
        boolean b3 = num.charAt(1) == num.charAt(2);
        if (b1 && b2 && b3) return 2;
        if (b1 || b2 || b3) return 1;
        return 0;
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, String p0,
            boolean hasAnswer, String p1) {
        System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
        System.out.println("]");
        PhoneNumbers obj;
        String answer;
        obj = new PhoneNumbers();
        long startTime = System.currentTimeMillis();
        answer = obj.bestNumber(p0);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0
                + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + "\"" + p1 + "\"");
        }
        System.out.println("Your answer:");
        System.out.println("\t" + "\"" + answer + "\"");
        if (hasAnswer) {
            res = answer.equals(p1);
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        String p0;
        String p1;

        // ----- test 0 -----
        p0 = "5088638";
        p1 = "50-88-638";
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = "0123456789";
        p1 = "01-23-45-67-89";
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = "09";
        p1 = "09";
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = "54545454545454545454";
        p1 = "54-545-454-545-454-545-454";
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = "00110001011100010111";
        p1 = "00-11-00-010-11-10-00-101-11";
        all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
        // ------------------

        if (all_right) {
            System.out
                    .println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
